Update gen_update_metadata.yml

diff --git a/.github/workflows/gen_update_metadata.yml b/.github/workflows/gen_update_metadata.yml
--- a/.github/workflows/gen_update_metadata.yml
+++ b/.github/workflows/gen_update_metadata.yml
@@ -1,210 +1,102 @@
 name: 🐧🧬 Generate Metadata 🖳🧬
-#MAX_RUNTIME: 02 Minutes */10 * * * *
 
 on:
-  #push:
   workflow_dispatch:
   schedule:
-    - cron: "0,30 * * * *"  # Every 01 Hrs
+    - cron: "0,30 * * * *"  # Every 30 minutes
 
 jobs:
-#------------------------------------------------------------------------------------#
   gen-metadata:
     runs-on: ubuntu-latest
     permissions:
       contents: write
 
     steps:
-      ##Uncomment if Runner is running out of space
-      #- name: Debloat Runner
-      #  run: |
-      #    #Presets
-      #    set +x ; set +e
-      #    #--------------#
-      #    bash <(curl -qfsSL "https://pub.ajam.dev/repos/Azathothas/Arsenal/misc/Github/Runners/Ubuntu/debloat.sh")
-      #  continue-on-error: true
-
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
           path: master
-          filter: "blob:none" #https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
+          filter: "blob:none"
 
-      ##Uncomment if Runner needs more tools
-      #- name: Install Addons
-      #  run: |
-      #    #presets
-      #    set +x ; set +e
-      #    #-------------#
-      #    bash <(curl -qfsSL "https://pub.ajam.dev/repos/Azathothas/Arsenal/misc/Linux/install_bb_tools.sh")
-      #  continue-on-error: true
-
-      - name: Setup Env
+      - name: Setup Environment Variables
         run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          #tmp
-           SYSTMP="$(dirname $(mktemp -u))" && export SYSTMP="$SYSTMP"
-          #UA
-           USER_AGENT="$(curl -qfsSL 'https://pub.ajam.dev/repos/Azathothas/Wordlists/Misc/User-Agents/ua_chrome_macos_latest.txt')" && export USER_AGENT="$USER_AGENT"
-          #GH ENV
-           echo "SYSTMP=$SYSTMP" >> "$GITHUB_ENV"
-           echo "USER_AGENT=$USER_AGENT" >> "$GITHUB_ENV"
-          #Generator
-           rm -rf "$GITHUB_WORKSPACE/master/misc/cmd/modMetadata"
-           mkdir -p "$GITHUB_WORKSPACE/master/misc/cmd/modMetadata"
-           curl -qfsSL "https://raw.githubusercontent.com/xplshn/dbin/master/misc/cmd/modMetadata/modMetadata.go" -o "$GITHUB_WORKSPACE/master/misc/cmd/modMetadata/modMetadata.go"
-          #-------------#
-        continue-on-error: true
+          SYSTMP=$(dirname $(mktemp -u))
+          USER_AGENT=$(curl -sL 'https://pub.ajam.dev/repos/Azathothas/Wordlists/Misc/User-Agents/ua_chrome_macos_latest.txt')
+          echo "SYSTMP=$SYSTMP" >> $GITHUB_ENV
+          echo "USER_AGENT=$USER_AGENT" >> $GITHUB_ENV
+        shell: sh
 
       - name: Install Golang
         run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          pushd "$(mktemp -d)" >/dev/null
-          echo "yes" | bash <(curl -qfsSL "https://git.io/go-installer")
-          popd >/dev/null
-        continue-on-error: true
+          mkdir -p /tmp/go-install
+          curl -sL "https://git.io/go-installer" | bash -s -- -v latest -i /tmp/go-install
+          echo "PATH=/tmp/go-install/bin:$PATH" >> $GITHUB_ENV
+        shell: sh
 
-      - name: Download and Run modMetadataAIO (0.5x)
+      - name: Run Metadata Generators
         run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          mkdir -p "$GITHUB_WORKSPACE/master/misc/cmd/modMetadataAIO"
-          curl -qfsSL "https://raw.githubusercontent.com/xplshn/dbin/master/misc/cmd/modMetadataAIO/modMetadataAIO.go" -o "$GITHUB_WORKSPACE/master/misc/cmd/modMetadataAIO/modMetadataAIO.go"
-          pushd "$GITHUB_WORKSPACE/master/misc/cmd/modMetadataAIO" >/dev/null
-          #Build
-           go mod init "github.com/xplshn/dbin/misc/cmd/modMetadataAIO" ; go mod tidy
-           GOOS="linux" GOARCH="amd64" CGO_ENABLED="0" go build -v -ldflags="-buildid= -s -w -extldflags '-static'" -o "./modMetadataAIO"
-          #Run
-           "./modMetadataAIO"
-          #Cleanup
-           find . -type f ! -name "*.json" -delete
-          #Sanity check
-           if find . -maxdepth 1 -name "*.json" -type f -size +0b | grep -q .; then
-               export HAS_META="TRUE"
-               echo "HAS_META=$HAS_META" >> "$GITHUB_ENV"
-           else
-               export HAS_META="FALSE"
-               echo "HAS_META=$HAS_META" >> "$GITHUB_ENV"
-           fi
-          #End
-           popd >/dev/null
-        continue-on-error: true
+          run_generator() {
+            script_url="$1"
+            folder_name="$2"
 
-      - name: Download and Run modMetadataAIO-ng (0.6x)
-        run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          mkdir -p "$GITHUB_WORKSPACE/master/misc/cmd/modMetadataAIO-ng"
-          curl -qfsSL "https://raw.githubusercontent.com/xplshn/dbin/master/misc/cmd/modMetadataAIO-ng/modMetadataAIO-ng.go" -o "$GITHUB_WORKSPACE/master/misc/cmd/modMetadataAIO-ng/modMetadataAIO-ng.go"
-          pushd "$GITHUB_WORKSPACE/master/misc/cmd/modMetadataAIO-ng" >/dev/null
-          #Build
-           go mod init "github.com/xplshn/dbin/misc/cmd/modMetadataAIO-ng" ; go mod tidy
-           GOOS="linux" GOARCH="amd64" CGO_ENABLED="0" go build -v -ldflags="-buildid= -s -w -extldflags '-static'" -o "./modMetadataAIO-ng"
-          #Run
-           "./modMetadataAIO-ng"
-          #Cleanup
-           find . -type f ! -name "*.json" -delete
-          #Sanity check
-           if find . -maxdepth 1 -name "*.json" -type f -size +0b | grep -q .; then
-               export HAS_META="TRUE"
-               echo "HAS_META=$HAS_META" >> "$GITHUB_ENV"
-           else
-               export HAS_META="FALSE"
-               echo "HAS_META=$HAS_META" >> "$GITHUB_ENV"
-           fi
-          #End
-           popd >/dev/null
-        continue-on-error: true
+            mkdir -p "$GITHUB_WORKSPACE/master/misc/cmd/$folder_name"
+            curl -sL "$script_url" -o "$GITHUB_WORKSPACE/master/misc/cmd/$folder_name/main.go"
+            cd "$GITHUB_WORKSPACE/master/misc/cmd/$folder_name"
 
-      - name: Ensure Healthy Commit Nums (RESET ON >= 70)
+            go mod init "github.com/xplshn/$folder_name" && go mod tidy
+            go run ./main.go
+
+            # Check if JSON files were generated
+            if find . -name "*.json" -type f -size +0b | grep -q .; then
+              echo "HAS_META=TRUE" >> $GITHUB_ENV
+            else
+              echo "HAS_META=FALSE" >> $GITHUB_ENV
+            fi
+
+            # Clean up intermediate files
+            find . -type f ! -name "*.json" -delete
+          }
+
+          run_generator "https://raw.githubusercontent.com/xplshn/dbin/master/misc/cmd/modMetadataAIO/modMetadataAIO.go" "modMetadataAIO"
+          run_generator "https://raw.githubusercontent.com/xplshn/dbin/master/misc/cmd/modMetadataAIO-ng/modMetadataAIO-ng.go" "modMetadataAIO-ng"
+          run_generator "https://raw.githubusercontent.com/xplshn/dbin/master/misc/cmd/AM-support/meta-to-am.go" "AM-support"
+        shell: sh
+
+      - name: Check Commit Numbers and Reset if Necessary
         if: env.HAS_META == 'TRUE'
         run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          pushd "$(mktemp -d)" > /dev/null 2>&1 && git clone --filter="blob:none" "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
-          cd "$(find . -maxdepth 1 -type d -exec basename {} \; | grep -Ev '^\.$' | xargs -I {} realpath {})"
-          CLONED_DIR="$(realpath .)" && export CLONED_DIR="$CLONED_DIR"
-          COMMIT_NUMS="$(git rev-list --count HEAD)" && export COMMIT_NUMS="$COMMIT_NUMS"
-          popd > /dev/null 2>&1 ; rm -rf "$CLONED_DIR" 2>/dev/null
-          cd "$GITHUB_WORKSPACE/master"
-          if [ "$COMMIT_NUMS" -gt 70 ]; then
-              echo -e "\n[+] Total number of commits exceeds 70. ($COMMIT_NUMS)\n"
-              cd "$GITHUB_WORKSPACE/master"
-              git config "user.name" "xplshn"
-              git config "user.email" "xplshn@murena.io"
-              git checkout --orphan temp
-              git add --all --verbose && git commit -m "Reset ALL Commits (Re:Init)"
-              git branch -D "master"
-              git branch -m "master"
-              git push --set-upstream origin master --force
-              echo "RESET_HISTORY=YES" >> "$GITHUB_ENV"
-          else
-              echo -e "\n[+] Total number of commits looks healthy. ($COMMIT_NUMS)\n"
-              echo "RESET_HISTORY=NO" >> "$GITHUB_ENV"
-          fi
-          pushd "$GITHUB_WORKSPACE/master" >/dev/null 2>&1 && git pull origin master && popd >/dev/null 2>&1
-        continue-on-error: true
+          git fetch --depth=1
+          COMMIT_NUMS=$(git rev-list --count HEAD)
 
-      - name: Download and run AM-compat metadata generator (for AM to support the AppBundleHUB repo)
-        run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          mkdir -p "$GITHUB_WORKSPACE/master/misc/cmd/AM-support"
-          curl -qfsSL "https://raw.githubusercontent.com/xplshn/dbin/master/misc/cmd/AM-support/meta-to-am.go" -o "$GITHUB_WORKSPACE/master/misc/cmd/AM-support/meta-to-am.go"
-          pushd "$GITHUB_WORKSPACE/master/misc/AM-support/meta-to-am.go" >/dev/null
-          #Build
-           go mod init "github.com/xplshn/dbin/misc/cmd/AM-support/meta-to-am.go" ; go mod tidy
-           GOOS="linux" GOARCH="amd64" CGO_ENABLED="0" go build -v -ldflags="-buildid= -s -w -extldflags '-static'" -o "./meta-to-am.go"
-          #Run
-           "./meta-to-am.go"
-          #Cleanup
-           find . -type f ! -name "*.json" -delete
-          #Sanity check
-           if find . -maxdepth 1 -name "*.json" -type f -size +0b | grep -q .; then
-               export HAS_META="TRUE"
-               echo "HAS_META=$HAS_META" >> "$GITHUB_ENV"
-           else
-               export HAS_META="FALSE"
-               echo "HAS_META=$HAS_META" >> "$GITHUB_ENV"
-           fi
-          #End
-           popd >/dev/null
-        continue-on-error: true
+          if [ "$COMMIT_NUMS" -gt 70 ]; then
+            git checkout --orphan temp
+            git add --all
+            git commit -m "Reset ALL Commits (Re:Init)"
+            git branch -D master
+            git branch -m master
+            git push origin master --force
+            echo "RESET_HISTORY=YES" >> $GITHUB_ENV
+          else
+            echo "RESET_HISTORY=NO" >> $GITHUB_ENV
+          fi
+        shell: sh
 
       - name: Get DateTime
         if: env.HAS_META == 'TRUE'
         run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          # Date Time
           UTC_TIME=$(TZ='UTC' date +'%Y-%m-%d (%I:%M:%S %p)')
           echo "UTC_TIME=$UTC_TIME" >> $GITHUB_ENV
-        continue-on-error: true
+        shell: sh
 
       - uses: stefanzweifel/git-auto-commit-action@v5
         if: env.HAS_META == 'TRUE'
         with:
           repository: ./master
-          commit_user_name: xplshn # defaults to "github-actions[bot]"
-          commit_user_email: xplshn@murena.io # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
+          commit_user_name: xplshn
+          commit_user_email: xplshn@murena.io
           commit_message: "✅ Updated (Metadata) 🛍️🧬 <-- ${{ env.UTC_TIME }} ⌚"
-          #push_options: '--force'
-        continue-on-error: true
 
-      - name: Exit & Fail
+      - name: Exit & Fail if Metadata Generation Failed
         if: env.HAS_META == 'FALSE'
-        run: |
-          #presets
-          set +x ; set +e
-          #-------------#
-          exit 1
-        continue-on-error: false
+        run: exit 1
+        shell: sh
